import { describe, expect, it } from 'vitest'
import { formatAdif } from './formatter'

describe('formatAdif · 结构', () => {
  it('空对象返回空字符串', () => {
    expect(formatAdif({})).toBe('')
  })

  it('仅记录', () => {
    const out = formatAdif({ records: [{ call: 'BA0AX' }] })
    expect(out).toBe('<CALL:5>BA0AX <EOR>\n')
  })

  it('头部 + 记录', () => {
    const out = formatAdif({
      header: { text: 'Generated by FmoDeck', adif_ver: '3.1.0' },
      records: [{ call: 'BA0AX', mode: 'FM' }]
    })
    expect(out).toBe(
      'Generated by FmoDeck\n<ADIF_VER:5>3.1.0\n<EOH>\n<CALL:5>BA0AX <MODE:2>FM <EOR>\n'
    )
  })

  it('多条记录', () => {
    const out = formatAdif({
      records: [{ call: 'BA0AX' }, { call: 'BY4SDL' }]
    })
    expect(out).toBe('<CALL:5>BA0AX <EOR>\n<CALL:6>BY4SDL <EOR>\n')
  })

  it('头部文本为空则不输出', () => {
    const out = formatAdif({
      header: { text: '', adif_ver: '3.1.0' },
      records: [{ call: 'BA0AX' }]
    })
    expect(out).toBe('<ADIF_VER:5>3.1.0\n<EOH>\n<CALL:5>BA0AX <EOR>\n')
  })
})

describe('formatAdif · UTF-8 字节长度', () => {
  it('中文字段长度为字节数', () => {
    const out = formatAdif({ records: [{ comment: '测试' }] })
    expect(out).toBe('<COMMENT:6>测试 <EOR>\n')
  })

  it('混合中英文', () => {
    const out = formatAdif({ records: [{ call: 'BA0AX', comment: 'BA0AX 你好' }] })
    expect(out).toBe('<CALL:5>BA0AX <COMMENT:12>BA0AX 你好 <EOR>\n')
  })

  it('标签名大写输出', () => {
    const out = formatAdif({ records: [{ app_fmo_comment_utf8: '测试' }] })
    expect(out).toContain('<APP_FMO_COMMENT_UTF8:6>测试')
  })
})
